experimental_log_batching_enabled = false
Limit = 0

[keys]
  up = ["up", "k"]
  down = ["down", "j"]
  jump_to_parent = ["J"]
  jump_to_working_copy = ["@"]
  apply = ["enter"]
  cancel = ["esc"]
  toggle_select = [" "]
  new = ["n"]
  commit = ["c"]
  refresh = ["ctrl+r"]
  abandon = ["a"]
  diff = ["d"]
  quit = ["q"]
  help = ["?"]
  describe = ["D"]
  edit = ["e"]
  diffedit = ["E"]
  absorb = ["A"]
  split = ["s"]
  undo = ["u"]
  evolog = ["v"]
  revset = ["L"]
  quick_search = ["/"]
  quick_search_cycle = ["'"]
  custom_commands = ["x"]
  leader = ["\\"]
  suspend = ["ctrl+z"]
  [keys.rebase]
    mode = ["r"]
    revision = ["r"]
    source = ["s"]
    branch = ["B"]
    after = ["a"]
    before = ["b"]
    onto = ["d"]
    insert = ["i"]
  [keys.duplicate]
    mode = ["y"]
    after = ["a"]
    before = ["b"]
    onto = ["d"]
  [keys.squash]
    mode = ["S"]
    keep_emptied = ["e"]
    interactive = ["i"]
  [keys.details]
    mode = ["l"]
    close = ["h"]
    split = ["s"]
    restore = ["r"]
    absorb = ["A"]
    diff = ["d"]
    select = ["m", " "]
    revisions_changing_file = ["*"]
  [keys.preview]
    mode = ["p"]
    scroll_up = ["ctrl+p"]
    scroll_down = ["ctrl+n"]
    half_page_down = ["ctrl+d"]
    half_page_up = ["ctrl+u"]
    expand = ["ctrl+h"]
    shrink = ["ctrl+l"]
  [keys.bookmark]
    mode = ["b"]
    set = ["B"]
    delete = ["d"]
    move = ["m"]
    forget = ["f"]
    track = ["t"]
    untrack = ["u"]
  [keys.inline_describe]
    mode = ["enter"]
    accept = ["alt+enter", "ctrl+s"]
  [keys.git]
    mode = ["g"]
    push = ["p"]
    fetch = ["f"]
  [keys.oplog]
    mode = ["o"]
    restore = ["r"]

[ui]
  highlight_light = "#a0a0a0"
  highlight_dark = "#282a36"
  auto_refresh_interval = 0
  [ui.colors]
    [ui.colors."confirmation dimmed"]
      fg = "white"
      bg = ""
      bold = false
      underline = false
    [ui.colors."confirmation selected"]
      fg = "bright white"
      bg = "blue"
      bold = true
      underline = false
    [ui.colors."confirmation text"]
      fg = "magenta"
      bg = ""
      bold = true
      underline = false
    [ui.colors."details selected"]
      fg = ""
      bg = "bright black"
      bold = false
      underline = false
    [ui.colors.dimmed]
      fg = "bright black"
      bg = ""
      bold = false
      underline = false
    [ui.colors.error]
      fg = "red"
      bg = ""
      bold = false
      underline = false
    [ui.colors."help title"]
      fg = "green"
      bg = ""
      bold = true
      underline = false
    [ui.colors.matched]
      fg = "cyan"
      bg = ""
      bold = false
      underline = false
    [ui.colors."menu matched"]
      fg = "magenta"
      bg = ""
      bold = true
      underline = false
    [ui.colors."menu selected"]
      fg = "cyan"
      bg = ""
      bold = true
      underline = false
    [ui.colors."menu title"]
      fg = "230"
      bg = "62"
      bold = true
      underline = false
    [ui.colors."revset text"]
      fg = "green"
      bg = ""
      bold = true
      underline = false
    [ui.colors."revset title"]
      fg = "magenta"
      bg = ""
      bold = false
      underline = false
    [ui.colors.selected]
      fg = "cyan"
      bg = "bright black"
      bold = false
      underline = false
    [ui.colors.shortcut]
      fg = "magenta"
      bg = ""
      bold = false
      underline = false
    [ui.colors.source_marker]
      fg = "black"
      bg = "cyan"
      bold = false
      underline = false
    [ui.colors."status title"]
      fg = "black"
      bg = "magenta"
      bold = true
      underline = false
    [ui.colors.success]
      fg = "green"
      bg = ""
      bold = false
      underline = false
    [ui.colors.target_marker]
      fg = "black"
      bg = "red"
      bold = true
      underline = false
    [ui.colors.text]
      fg = "white"
      bg = ""
      bold = false
      underline = false
    [ui.colors.title]
      fg = "magenta"
      bg = ""
      bold = true
      underline = false

[preview]
  extra_args = []
  revision_command = ["show", "--color", "always", "-r", "$change_id"]
  oplog_command = ["op", "show", "$operation_id", "--color", "always"]
  file_command = ["diff", "--color", "always", "-r", "$change_id", "$file"]
  show_at_start = false
  width_percentage = 50.0
  width_increment_percentage = 5.0

[oplog]
  limit = 200

[custom_commands]
